import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Jugnu: login",
  description: "Generated by Gugnu",
}; 

export default function layout({children}:Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>{children}</>
  )
}
